package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.sql.ResultSet;
import java.sql.Statement;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class UsersController {
	@FXML
	private AnchorPane searchPageAnchorPane;
	@FXML
	private TextField searchTextField;
	@FXML
	private Button searchButton;
	@FXML
	private TableView<Users> tvUsers;
	@FXML
	private TableColumn<Users, Integer> colID;
	@FXML
	private TableColumn<Users, String> colUsername;
	@FXML
	private TableColumn<Users, String> colFirstName;
	@FXML
	private TableColumn<Users, String> colLastName;
	@FXML
	private TableColumn<Users, String> colAddress;
	@FXML
	private TableColumn<Users, Integer> colRole;
	@FXML
	private Button createUserBtn;
	@FXML
	private Button updateUserBtn;
	@FXML
	private Button deleteUserBtn;
	@FXML
	private TextField tfID;
	@FXML
	private TextField tfUsername;
	@FXML
	private TextField tfFirstName;
	@FXML
	private TextField tfRole;
	@FXML
	private TextField tfAddress;
	@FXML
	private Button clearSidePanel;
	@FXML
	private TextField tfLastName;
	@FXML
	private TextField tfTelephone;
	@FXML
	private TextField tfAge;

	// Event Listener on AnchorPane[#searchPageAnchorPane].onMouseClicked
	@FXML
	public void handleMouseClick(MouseEvent event) {
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#searchButton].onAction
	@FXML
	public void searchUsers(ActionEvent event) {
		if (getAllUsers().size() > 0) {
			displayAllUsers();
		} else {
			this.tvUsers.setItems(null);
		}
	}
	
	public ObservableList<Users> getAllUsers() {
		ObservableList<Users> userList = FXCollections.observableArrayList();
		String searchWord = "%" + searchTextField.getText() + "%";
		String query = String.format("SELECT * FROM users where username like '%s' ", searchWord);
		
		Statement statement;
		ResultSet resultSet;
		
		try {
			statement = DatabaseConnection.getInstance().createStatement();
			resultSet = statement.executeQuery(query);
			Users user;
			while (resultSet.next()) {
				user = new Users(
						resultSet.getInt("id"),
						resultSet.getInt("age"),
						resultSet.getString("username"),
						resultSet.getString("firstname"),
						resultSet.getString("lastname"),
						resultSet.getString("address"),
						resultSet.getString("telephone"),
						resultSet.getInt("role")
						);			
				userList.add(user);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		return userList;
	}
	
	public void displayAllUsers() {
		ObservableList<Users> list = getAllUsers();
		
		this.colID.setCellValueFactory(new PropertyValueFactory<Users, Integer>("id"));
		this.colUsername.setCellValueFactory(new PropertyValueFactory<Users, String>("username"));
		this.colFirstName.setCellValueFactory(new PropertyValueFactory<Users, String>("firstName"));
		this.colLastName.setCellValueFactory(new PropertyValueFactory<Users, String>("lastName"));
		this.colAddress.setCellValueFactory(new PropertyValueFactory<Users, String>("fullAddress"));
		this.colRole.setCellValueFactory(new PropertyValueFactory<Users, Integer>("role"));
		
		this.tvUsers.setItems(list);
	}
	
	
	// Event Listener on TableView[#tvBooks].onMouseClicked
	@FXML
	public void passDetailsToTextfields(MouseEvent event) {
		Users selectedUser = this.tvUsers.getSelectionModel().getSelectedItem();
		tfID.setText(selectedUser.getId());
		tfUsername.setText(selectedUser.getUsername());
		tfFirstName.setText(selectedUser.getFirstName());
		tfLastName.setText(selectedUser.getLastName());
		tfAddress.setText(selectedUser.getFullAddress());
		tfRole.setText(selectedUser.getRole());
		tfTelephone.setText(selectedUser.getTelephone());
		tfAge.setText(selectedUser.getAge());
	}
	
	
	// Event Listener on Button[#createUserBtn].onAction
	@FXML
	public void createUser(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#updateUserBtn].onAction
	@FXML
	public void updateUser(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#deleteUserBtn].onAction
	@FXML
	public void deleteUser(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#clearSidePanel].onAction
	@FXML
	public void clearSidePanel(ActionEvent event) {
		tfID.clear();
		tfUsername.clear();
		tfFirstName.clear();
		tfLastName.clear();
		tfAddress.clear();
		tfRole.clear();
		tfTelephone.clear();
		tfAge.clear();
	}
}
